# Copyright 2025 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import asyncio
import json
import logging
import os
from enum import Enum
import re
import textwrap
from typing import Any, Dict, Literal, Optional, Tuple
from uuid import uuid4

from omegaconf import OmegaConf
import torch
from PIL import Image

from verl.experimental.agent_loop.agent_loop import (
    AgentLoopBase,
    AgentLoopOutput,
    register,
)
from verl.experimental.agent_loop.tool_parser import FunctionCall, ToolParser
from verl.experimental.agent_loop.utils import build_gpt_oss_tool_response_text
from verl.interactions.base import BaseInteraction
from verl.interactions.utils.interaction_registry import initialize_interactions_from_config
from verl.tools.schemas import ToolResponse
from verl.tools.utils.tool_registry import initialize_tools_from_config
from verl.utils.profiler import simple_timer
from verl.utils.rollout_trace import rollout_trace_op
from verl.workers.rollout.replica import TokenOutput

logger = logging.getLogger(__file__)
logger.setLevel(os.getenv("VERL_LOGGING_LEVEL", "WARN"))


class AgentState(Enum):
    PENDING = "pending"
    GENERATING = "generating"
    PROCESSING_TOOLS = "processing_tools"
    TERMINATED = "terminated"
    INTERACTING = "interacting"


USER_TOOL_PATTERN = re.compile(r'\b(?:user|tool)\s*(?=<tool_response>)')
ASSISTANT_PATTERN = re.compile(r'\bassistant\s*(?=<think>)')
SPACING_PATTERN = re.compile(r'\n{3,}')


def process_generation_to_code(gen: str) -> str:
    return textwrap.dedent(gen).strip()

def reattach_stop_string_universal(generated_text: str, stop_mapping: dict[str, str]) -> str:
    """
    Deduces and reattaches the correct stop string by finding the last opened block.
    
    Args:
        generated_text: The raw text generated by the engine.
        stop_mapping: A dict mapping the START marker to its expected STOP marker.
                      e.g., {
                          "<tool_call>": "</tool_call>", 
                          "<code_block>": "</code_block>",
                          "```python": "```",
                          "Action:": "Observation:"
                      }
    """
    last_start_idx = -1
    active_stop_str = ""
    active_start_str = ""
    
    for start_str, stop_str in stop_mapping.items():
        idx = generated_text.rfind(start_str)
        
        if idx > last_start_idx:
            last_start_idx = idx
            active_stop_str = stop_str
            active_start_str = start_str
            
    if last_start_idx == -1:
        return generated_text
        
    text_after_start = generated_text[last_start_idx + len(active_start_str):]

    if active_stop_str not in text_after_start:
        

        if generated_text.endswith(active_stop_str):
            return generated_text
             
        return generated_text + active_stop_str
        
    return generated_text


class AgentData:
    """Encapsulates all state variables for the agent loop. AgentData is passed to tool calling in case that
    tool may need to access full history state. User can store any tool session data in `extra_fields`."""

    def __init__(
        self,
        messages: list[dict[str, Any]],
        image_data: list[Image.Image],
        video_data: list[tuple[torch.Tensor, dict[str, Any]]],
        metrics: dict[str, Any],
        request_id: str,
        tools_kwargs: dict[str, Any],
        interaction: Optional[BaseInteraction] = None,
        interaction_kwargs: Optional[dict[str, Any]] = None,
    ):
        self.messages = messages
        self.image_data = image_data
        self.video_data = video_data
        self.metrics = metrics
        self.request_id = request_id
        self.tools_kwargs = tools_kwargs
        self.interaction = interaction
        self.interaction_kwargs = interaction_kwargs or {}

        # State variables
        self.prompt_ids: list[int] = []
        self.response_ids: list[int] = []
        self.response_mask: list[int] = []
        self.response_logprobs: list[float] = []
        self.turn_scores: list[float] = []
        self.tool_rewards: list[float] = []
        self.user_turns = 0
        self.assistant_turns = 0
        self.last_successful_tool_idx = 0
        self.t_pivot = 0

        # Temporary state for tool calls
        self.tool_calls: list[FunctionCall] = []

        self.routed_experts = None

        # Extra fields for dynamic addition, e.g., tool session data
        self.extra_fields: dict[str, Any] = {}


def get_template_prefill_string(tokenizer: Any, chat_kwargs: Dict[str, Any]) -> str:
    """
    Determines exactly what the tokenizer appends when starting an assistant turn.
    """
    dummy_messages = [{"role": "user", "content": "____MARKER____"}]
    
    # 1. Get prompt without generation header
    base = tokenizer.apply_chat_template(dummy_messages, add_generation_prompt=False, tokenize=False, **chat_kwargs)
    
    # 2. Get prompt with generation header
    full = tokenizer.apply_chat_template(dummy_messages, add_generation_prompt=True, tokenize=False, **chat_kwargs)
    
    # 3. The difference is the pre-fill string (e.g., '<|im_start|>assistant\n<think>\n')
    return full[len(base):]


def extract_final_answer_and_status(
    text: str, 
    answer_start_tag: str = "<final_answer>", 
    answer_end_tag: str = "</final_answer>"
) -> Tuple[str, bool]:
    """
    Isolates the final answer. 
    Returns: (extracted_text, is_structurally_sound)
    """
    if not text:
        return "", False

    # 1. Primary Check: The explicit user-defined tags
    # pattern = fr"{re.escape(answer_start_tag)}(.*?){re.escape(answer_end_tag)}"
    # tag_matches = re.findall(pattern, text, re.DOTALL | re.IGNORECASE)
    # if tag_matches:
    #     return tag_matches[-1].strip(), True

    has_start = answer_start_tag in text
    has_end = answer_end_tag in text

    if has_start:
        # Isolate everything after the LAST occurrence of the start tag
        content = text.split(answer_start_tag)[-1]
        
        # If the end tag exists, chop off everything after it
        if has_end:
            content = content.split(answer_end_tag)[0]
        
        # Return the extracted content. 
        # is_structurally_sound is strictly True ONLY if both tags exist.
        return content.strip(), True
        
    # 2. Secondary Check: The standard LaTeX \boxed{} notation
    boxed_matches = re.findall(r"\\boxed\{((?:[^{}]|(?:\{[^{}]*\}))*)\}", text)
    if boxed_matches:
        return boxed_matches[-1].strip(), True

    # 3. Tertiary Check: Common markdown "Final Answer" headers
    header_matches = re.findall(r"(?i)(?:final\s*answer|answer)\s*:\s*\**\s*(.+)", text)
    if header_matches:
        return header_matches[-1].strip(), True
    
    # 4. Absolute Fallback: Return the full CoT string
    return text.strip(), False


@register("tool_agent")
class ToolAgentLoop(AgentLoopBase):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Initialize tools from config file
        self.max_user_turns = self.rollout_config.multi_turn.max_user_turns
        self.max_assistant_turns = self.rollout_config.multi_turn.max_assistant_turns
        self.max_parallel_calls = self.rollout_config.multi_turn.max_parallel_calls
        self.max_tool_response_length = self.rollout_config.multi_turn.max_tool_response_length
        self.tool_response_truncate_side = self.rollout_config.multi_turn.tool_response_truncate_side
        tool_config_path = self.rollout_config.multi_turn.tool_config_path
        tool_list = initialize_tools_from_config(tool_config_path) if tool_config_path else []

        prefill_str = get_template_prefill_string(self.tokenizer, chat_kwargs={})
        self.needs_reasoning_prefill = "<think>" in prefill_str

        rm_config = self.config.reward
        self.reward_kwargs = rm_config.get("reward_kwargs", {})
        self.role_configs = self.reward_kwargs.get("role_configs", {})
        final_answer_role = self.role_configs.get("final_answer", { "start_tag": "<final_answer>", "end_tag": "</final_answer>" })
        self.final_answer_start_tag = final_answer_role.get("start_tag")
        self.final_answer_end_tag = final_answer_role.get("end_tag")

        self.target_role: Literal["assistant", "tool", "user"] = self.reward_kwargs.get("target_role", "tool")
        self.use_mt_collapse_masking = self.reward_kwargs.get("use_collapse_masking", False)
        

        self.tools = { tool.name: tool for tool in tool_list }
        self.tool_schemas = [
            tool.tool_schema.model_dump(exclude_unset=True, exclude_none=True)
            for tool in tool_list for tool in tool_list if getattr(tool, "tool_schema", None) is not None
        ]
        raw_tool_cfg = OmegaConf.load(self.rollout_config.multi_turn.tool_config_path)
        resolved_cfg = OmegaConf.to_container(raw_tool_cfg, resolve=True)

        if isinstance(resolved_cfg, list):
            self.tool_configs = resolved_cfg
        elif isinstance(resolved_cfg, dict) and 'tools' in resolved_cfg:
            self.tool_configs = resolved_cfg['tools']
        else:
            # If it's just a single tool dict not in a list
            self.tool_configs = [resolved_cfg]

        self.tool_parser = ToolParser.get_tool_parser(
            self.rollout_config.multi_turn.format, 
            self.tokenizer,
            self.tool_configs[0]["config"], 
        )
        self.tool_parser_name = self.rollout_config.multi_turn.format

        self.prompt_length = self.rollout_config.prompt_length
        self.response_length = self.rollout_config.response_length

        # Initialize interactions from config file
        self.interaction_config_file = self.rollout_config.multi_turn.interaction_config_path
        if self.interaction_config_file:
            self.interaction_map: dict[str, BaseInteraction] = self._initialize_interactions(
                self.interaction_config_file
            )

    @rollout_trace_op
    async def run(self, sampling_params: dict[str, Any], **kwargs) -> AgentLoopOutput:
        messages = list(kwargs["raw_prompt"])

        # extract images and videos from messages
        multi_modal_data = await self.process_vision_info(messages)
        images = multi_modal_data.get("images")
        videos = multi_modal_data.get("videos")

        metrics = {}
        request_id = uuid4().hex
        tools_kwargs = kwargs.get("tools_kwargs", {})

        # Initialize interaction if needed
        interaction = None
        interaction_kwargs = {}
        if self.interaction_config_file:
            interaction_kwargs = kwargs["extra_info"]["interaction_kwargs"]
            if "name" not in interaction_kwargs:
                raise ValueError("'name' key is required in interaction_kwargs")
            interaction_name = interaction_kwargs["name"]
            if interaction_name not in self.interaction_map:
                raise ValueError(
                    f"Interaction '{interaction_name}' not found in interaction_map. Available interactions: "
                    f"{list(self.interaction_map.keys())}"
                )
            interaction = self.interaction_map[interaction_name]
            await interaction.start_interaction(request_id, **interaction_kwargs)
        # Create AgentData instance to encapsulate all state
        agent_data = AgentData(
            messages=messages,
            image_data=images,
            video_data=videos,
            metrics=metrics,
            request_id=request_id,
            tools_kwargs=tools_kwargs,
            interaction=interaction,
            interaction_kwargs=interaction_kwargs,
        )

        # State machine loop
        state = AgentState.PENDING
        while state != AgentState.TERMINATED:
            if state == AgentState.PENDING:
                state = await self._handle_pending_state(agent_data, sampling_params)
            elif state == AgentState.GENERATING:
                state = await self._handle_generating_state(agent_data, sampling_params)
            elif state == AgentState.PROCESSING_TOOLS:
                state = await self._handle_processing_tools_state(agent_data)
            elif state == AgentState.INTERACTING:
                state = await self._handle_interacting_state(agent_data)
            else:
                logger.error(f"Invalid state: {state}")
                state = AgentState.TERMINATED

        # Finalize output
        response_ids = agent_data.prompt_ids[-len(agent_data.response_mask) :]
        prompt_ids = agent_data.prompt_ids[: len(agent_data.prompt_ids) - len(agent_data.response_mask)]
        multi_modal_data = {}
        if agent_data.image_data is not None:
            multi_modal_data["images"] = agent_data.image_data
        if agent_data.video_data is not None:
            multi_modal_data["videos"] = agent_data.video_data

        output: AgentLoopOutput = AgentLoopOutput(
            prompt_ids=prompt_ids,
            response_ids=response_ids[: self.response_length],
            response_mask=agent_data.response_mask[: self.response_length],
            multi_modal_data=multi_modal_data,
            response_logprobs=agent_data.response_logprobs[: self.response_length]
            if agent_data.response_logprobs
            else None,
            num_turns=agent_data.user_turns + agent_data.assistant_turns + 1,
            metrics=agent_data.metrics,
            routed_experts=agent_data.routed_experts,
            extra_fields=agent_data.extra_fields,
        )

        # hit_token_limit = len(agent_data.response_mask) >= self.response_length
        # hit_turn_limit = (self.max_assistant_turns and agent_data.assistant_turns >= self.max_assistant_turns) or \
        #                  (self.max_user_turns and agent_data.user_turns >= self.max_user_turns)
        
        # full_text = self.tokenizer.decode(response_ids, skip_special_tokens=True)
        # has_start_tag = self.final_answer_start_tag in full_text
        # has_end_tag = self.final_answer_end_tag in full_text

        # _, is_structurally_sound = extract_final_answer_and_status(
        #     text=full_text,
        #     answer_start_tag=self.final_answer_start_tag,
        #     answer_end_tag=self.final_answer_end_tag
        # )

        # if hit_token_limit or hit_turn_limit or not is_structurally_sound:
        #     # STRUCTURAL COLLAPSE: The model babbled endlessly or looped or just broken 
        #     # Shield the prefix up to the last known good state.
        #     agent_data.t_pivot = agent_data.last_successful_tool_idx
        # else:
        #     # STRUCTURAL SUCCESS: It finished its reasoning cleanly (emitted EOS).
        #     # Even if the math is wrong, this is NOT gibberish. Set pivot to the 
        #     # absolute end so the Bidirectional logic skips the masking.
        #     agent_data.t_pivot = len(agent_data.response_mask)

        output.extra_fields.update({
            "turn_scores": agent_data.turn_scores, 
            "tool_rewards": agent_data.tool_rewards,
            "tool_metrics": agent_data.extra_fields.get("tool_metrics", []),
            # "use_mt_collapse_masking": self.use_mt_collapse_masking
        })

        return output

    async def _handle_pending_state(self, agent_data: AgentData, sampling_params: dict[str, Any]) -> AgentState:
        """Handle the pending state: prepare the prompt and start generation."""
        prompt_ids = await self.apply_chat_template(
            agent_data.messages,
            tools=self.tool_schemas,
            images=agent_data.image_data,
            videos=agent_data.video_data,
        )
        agent_data.prompt_ids = prompt_ids
        return AgentState.GENERATING

    async def _handle_generating_state(
        self, agent_data: AgentData, sampling_params: dict[str, Any], ignore_termination: bool = False
    ) -> AgentState:
        """Handle the generating state: generate model response and check for tool calls."""
        add_messages: list[dict[str, Any]] = []

        with simple_timer("generate_sequences", agent_data.metrics):
            output: TokenOutput = await self.server_manager.generate(
                request_id=agent_data.request_id,
                prompt_ids=agent_data.prompt_ids,
                sampling_params=sampling_params,
                image_data=agent_data.image_data,
                video_data=agent_data.video_data,
            )
        # first time to set num_preempted
        if agent_data.metrics.get("num_preempted") is None:
            agent_data.metrics["num_preempted"] = output.num_preempted if output.num_preempted is not None else -1
        # then add num_preempted to the metrics
        else:
            agent_data.metrics["num_preempted"] += output.num_preempted if output.num_preempted is not None else 0

        if not agent_data.extra_fields:
            agent_data.extra_fields.update(output.extra_fields)
        else:
            # Multi-round calls, only update the maximum max_global_steps.
            max_global_steps = output.extra_fields.get("max_global_steps", None)
            if max_global_steps:
                agent_data.extra_fields["max_global_steps"] = max_global_steps

        agent_data.assistant_turns += 1
        agent_data.response_ids = output.token_ids
        
        engine_name = self.config.actor_rollout_ref.rollout.name
        include_stop_str_in_output = self.config.reward.reward_kwargs.get("include_stop_str_in_output", False)
        stop_string_mapping = self.config.reward.reward_kwargs.get("stop_string_mapping", {})
        
        # Only reattach if the engine strips them (i.e., NOT vllm)
        if engine_name != "vllm" and stop_string_mapping and include_stop_str_in_output:
            generated_text = await self.loop.run_in_executor(
                None, lambda: self.tokenizer.decode(agent_data.response_ids, skip_special_tokens=True) # type: ignore
            )

            missing_stop_str = reattach_stop_string_universal(generated_text, stop_string_mapping)
            
            if missing_stop_str:
                logger.info(f"Reattaching stripped stop string: {missing_stop_str}")
                missing_ids = await self.loop.run_in_executor(
                    None, lambda: self.tokenizer.encode(missing_stop_str, add_special_tokens=False) # type: ignore
                )
                
                agent_data.response_ids.extend(missing_ids)
                if output.log_probs:
                    output.log_probs.extend([0.0] * len(missing_ids))
        
        agent_data.prompt_ids += agent_data.response_ids
        agent_data.response_mask += [1] * len(agent_data.response_ids)
        if output.log_probs:
            agent_data.response_logprobs += output.log_probs

        if output.routed_experts is not None:
            agent_data.routed_experts = output.routed_experts

        # Check termination conditions
        if not ignore_termination and len(agent_data.response_mask) >= self.response_length:
            return AgentState.TERMINATED
        if self.max_assistant_turns and agent_data.assistant_turns >= self.max_assistant_turns:
            return AgentState.TERMINATED
        if self.max_user_turns and agent_data.user_turns >= self.max_user_turns:
            return AgentState.TERMINATED

        # Extract tool calls
        tools = [tool.tool_schema for tool in self.tools.values() if getattr(tool, "tool_schema", None) is not None]
        _, agent_data.tool_calls = await self.tool_parser.extract_tool_calls(agent_data.response_ids, tools)

        assistant_message = await self.loop.run_in_executor(
            None, lambda: self.tokenizer.decode(agent_data.response_ids, skip_special_tokens=True)
        )

        is_fresh_assistant_turn = (not agent_data.messages) or (agent_data.messages[-1]["role"] != "assistant")
        prefill_this_turn = self.needs_reasoning_prefill and is_fresh_assistant_turn

        # Restore the missing tag so the message history remains intact
        if prefill_this_turn and not assistant_message.lstrip().startswith("<think>"):
            assistant_message = "<think>\n" + assistant_message.lstrip()

        # Synchronize Message History
        if self.target_role == "assistant" and not is_fresh_assistant_turn:
            last_content = agent_data.messages[-1]["content"]
            if isinstance(last_content, str):
                agent_data.messages[-1]["content"] += assistant_message

            else:
                if last_content and last_content[-1]["type"] == "text":
                    last_content[-1]["text"] += assistant_message

                else:
                    last_content.append({"type": "text", "text": assistant_message})
        else:
            agent_data.messages.append({"role": "assistant", "content": assistant_message})

        # Handle interaction if needed
        # if self.interaction_config_file:
        #     assistant_message = await self.loop.run_in_executor(
        #         None, lambda: self.tokenizer.decode(agent_data.response_ids, skip_special_tokens=True)
        #     )
        #     add_messages.append({"role": "assistant", "content": assistant_message})
        #     agent_data.messages.extend(add_messages)

        # Determine next state
        if agent_data.tool_calls:
            return AgentState.PROCESSING_TOOLS

        elif self.interaction_config_file:
            return AgentState.INTERACTING

        else:
            return AgentState.TERMINATED

    async def _handle_processing_tools_state(self, agent_data: AgentData) -> AgentState:
        """Handle the processing tools state: execute tool calls and prepare tool responses."""
        add_messages: list[dict[str, Any]] = []
        new_images_this_turn: list[Any] = []  # Local variable instead of agent_data attribute
        new_videos_this_turn: list[Any] = []

        tasks = []
        tool_call_names = []
        for tool_call in agent_data.tool_calls[: self.max_parallel_calls]:
            tasks.append(self._call_tool(tool_call, agent_data.tools_kwargs, agent_data))
            tool_call_names.append(tool_call.name)

        with simple_timer("tool_calls", agent_data.metrics):
            responses = await asyncio.gather(*tasks)

        new_content_blocks = []

        # Process tool responses and update multi_modal_data
        # Removed: agent_data.new_images_this_turn = []
        for (tool_response, tool_reward, tool_meta), tool_name in zip(responses, tool_call_names):
            text_resp = tool_response.text or ""

            if self.target_role == "assistant":
                inline_text = text_resp if text_resp else ""

                if inline_text and self.needs_reasoning_prefill:
                    inline_text += "<think>\n"
            else:
                inline_text = ""

            if tool_reward is not None:
                agent_data.tool_rewards.append(tool_reward)

            if "tool_metrics" not in agent_data.extra_fields:
                agent_data.extra_fields["tool_metrics"] = []

            tool_meta["tool_name"] = tool_name
            tool_meta["assistant_turn"] = agent_data.assistant_turns
            tool_meta["user_turn"] = agent_data.user_turns
            tool_meta["parallel_idx"] = len(agent_data.extra_fields["tool_metrics"])

            agent_data.extra_fields["tool_metrics"].append(tool_meta)

            # Create message from tool response
            if tool_response.image or tool_response.video:
                # Multi-modal content with structured format
                if not getattr(self.processor, "image_processor", None):
                    raise ValueError(
                        "Multimedia data can only be processed by `processor`, but the processor is None. "
                        "This error is often caused if you are using a LLM model but your tool returns multimodal "
                        "data. Plase use a vlm as the base model."
                    )
                content_list = []
                if tool_response.image:
                    content_list.append({"type": "image"})
                    if isinstance(tool_response.image, list):
                        new_images_this_turn.extend([img for img in tool_response.image if img is not None])
                    elif tool_response.image is not None:
                        new_images_this_turn.append(tool_response.image)

                if tool_response.video:
                    content_list.append({"type": "video"})
                    if isinstance(tool_response.video, list):
                        new_videos_this_turn.extend([vid for vid in tool_response.video if vid is not None])
                    elif tool_response.video is not None:
                        new_videos_this_turn.append(tool_response.video)

                if text_resp:
                    content_list.append({"type": "text", "text": text_resp})

                if self.target_role in ["user", "tool"]:
                    add_messages.append({"role": self.target_role, "content": content_list})

                elif self.target_role == "assistant":
                    new_content_blocks.extend([c for c in content_list if c["type"] != "text"])
                    if inline_text:
                        new_content_blocks.append({"type": "text", "text": inline_text})

            else:
                if self.target_role in ["user", "tool"]:
                    add_messages.append({"role": self.target_role, "content": text_resp})

                elif self.target_role == "assistant":
                    if inline_text:
                        new_content_blocks.append({"type": "text", "text": inline_text})
                # add_messages.append({"role": self.target_role, "content": text_resp})
                # new_content_blocks.append({"type": "text", "text": inline_text})

            # Handle image data
            if tool_response.image:
                # Add new image data
                if isinstance(tool_response.image, list):
                    # Ensure all elements in the list are valid image objects
                    for img in tool_response.image:
                        if img is not None:  # Add a check to ensure the image is not None
                            new_images_this_turn.append(img)  # Using local variable
                else:
                    # Ensure the image is not None
                    if tool_response.image is not None:
                        new_images_this_turn.append(tool_response.image)  # Using local variable

            # Handle video data
            if tool_response.video:
                # Currently not supported, raise informative error
                logger.warning("Multimedia type 'video' is not currently supported. Only 'image' is supported.")
                raise NotImplementedError(
                    "Multimedia type 'video' is not currently supported. Only 'image' is supported."
                )

        if new_images_this_turn:
            if agent_data.image_data is None:
                agent_data.image_data = []
            elif not isinstance(agent_data.image_data, list):
                agent_data.image_data = [agent_data.image_data]
            agent_data.image_data.extend(new_images_this_turn)

        if new_videos_this_turn:
            if agent_data.video_data is None:
                agent_data.video_data = []
            elif not isinstance(agent_data.video_data, list):
                agent_data.video_data = [agent_data.video_data]
            agent_data.video_data.extend(new_videos_this_turn)

        if self.target_role in ["user", "tool"]:
            agent_data.messages.extend(add_messages)
            
            if self.tool_parser_name == "gpt-oss":
                logger.info("manually format tool responses for gpt-oss")
                tool_response_text = build_gpt_oss_tool_response_text(add_messages, tool_call_names)
                response_ids = await self.loop.run_in_executor(
                    None, lambda: self.tokenizer.encode(tool_response_text, add_special_tokens=False)
                )
            else:
                # Note that we have to pass None to the images and videos if there are no new images / videos
                # to stay compatible with downstream image processing logic!
                response_ids = await self.apply_chat_template(
                    add_messages,
                    images=new_images_this_turn if new_images_this_turn else None,
                    videos=new_videos_this_turn if new_videos_this_turn else None,
                    remove_system_prompt=True,
                )

                # # FULL HISTORY SLICING FIX
                # old_prompt_len = len(agent_data.prompt_ids)
                
                # # Apply template to the FULL history to guarantee correct tokenizer state
                # new_prompt_ids = await self.apply_chat_template(
                #     agent_data.messages,
                #     images=agent_data.image_data, 
                #     videos=agent_data.video_data, 
                #     remove_system_prompt=True,
                # )
                
                # # Strict mathematical extraction of the delta tokens
                # response_ids = new_prompt_ids[old_prompt_len:]

        elif self.target_role == "assistant":
            if agent_data.messages and agent_data.messages[-1]["role"] == "assistant":
                last_content = agent_data.messages[-1]["content"]
                if any(block["type"] != "text" for block in new_content_blocks):
                    if isinstance(last_content, str):
                        agent_data.messages[-1]["content"] = [{"type": "text", "text": last_content}] + new_content_blocks

                    else:
                        agent_data.messages[-1]["content"].extend(new_content_blocks)

                else:
                    combined_text = "".join(b["text"] for b in new_content_blocks)

                    if isinstance(last_content, str):
                        agent_data.messages[-1]["content"] += combined_text

                    else:
                        if last_content and last_content[-1]["type"] == "text":
                            last_content[-1]["text"] += combined_text

                        else:
                            agent_data.messages[-1]["content"].append({"type": "text", "text": combined_text})
            else:
                agent_data.messages.append({"role": "assistant", "content": new_content_blocks})


            text_delta = ""
            for block in new_content_blocks:
                if block["type"] == "text":
                    text_delta += block["text"]
            
            response_ids = await self.loop.run_in_executor(
                None, lambda: self.tokenizer.encode(text_delta, add_special_tokens=False)
            )

            # old_prompt_len = len(agent_data.prompt_ids)
            # new_prompt_ids = await self.apply_chat_template(
            #     agent_data.messages,
            #     images=agent_data.image_data,
            #     videos=agent_data.video_data,
            #     remove_system_prompt=True,
            # )

            # # Prevent token mismatch, usually max 1-5 tokens
            # safe_anchor = max(0, old_prompt_len - 5)
            # diverge_idx = safe_anchor
            # while diverge_idx < old_prompt_len and diverge_idx < len(new_prompt_ids):
            #     if agent_data.prompt_ids[diverge_idx] != new_prompt_ids[diverge_idx]:
            #         break
            #     diverge_idx += 1

            # response_ids = new_prompt_ids[diverge_idx:]

        if len(agent_data.response_mask) + len(response_ids) >= self.response_length:
            return AgentState.TERMINATED

        # start_token_idx = len(agent_data.response_mask)
        # if len(response_ids):
        #     start_token_idx += 1

        # Update prompt_ids and response_mask
        agent_data.prompt_ids += response_ids
        agent_data.response_mask += [0] * len(response_ids)

        if agent_data.response_logprobs:
            agent_data.response_logprobs += [0.0] * len(response_ids)

        agent_data.user_turns += 1

        # end_token_idx = len(agent_data.response_mask)

        # if self.use_mt_collapse_masking and agent_data.extra_fields.get("tool_metrics"):
        #     latest_metric = agent_data.extra_fields["tool_metrics"][-1] 

        #     latest_metric["start_token_idx"] = start_token_idx
        #     latest_metric["end_token_idx"] = end_token_idx

        return AgentState.GENERATING
    
    async def _handle_interacting_state(self, agent_data: AgentData) -> AgentState:
        """Handle the interacting state: get user input from interaction."""
        (
            should_terminate_sequence,
            interaction_responses,
            reward,
            metrics,
        ) = await agent_data.interaction.generate_response(
            agent_data.request_id, agent_data.messages, **agent_data.interaction_kwargs
        )
        agent_data.user_turns += 1

        add_messages: list[dict[str, Any]] = [{"role": "user", "content": interaction_responses}]
        agent_data.messages.extend(add_messages)

        if reward is not None:
            agent_data.turn_scores.append(reward)

        # Update prompt with user responses (similar to _handle_processing_tools_state)
        response_ids = await self.apply_chat_template(
            add_messages,
            remove_system_prompt=True,
        )

        # Update prompt_ids and response_mask
        agent_data.prompt_ids += response_ids
        agent_data.response_mask += [0] * len(response_ids)
        if agent_data.response_logprobs:
            agent_data.response_logprobs += [0.0] * len(response_ids)

        # double check prompt
        # Check termination condition
        if should_terminate_sequence:
            return AgentState.TERMINATED
        else:
            return AgentState.GENERATING
        

    async def _call_tool(
        self, tool_call: FunctionCall, tools_kwargs: dict[str, Any], agent_data: AgentData
    ) -> tuple[ToolResponse, float, dict]:
        """Call tool and return tool response."""
        tool, instance_id = None, None
        try:
            # TODO: append malformed tool_call to the prompt: invalid function name or arguments
            tool_name = tool_call.name
            tool_args = json.loads(tool_call.arguments)
            tool = self.tools[tool_name]
            kwargs = tools_kwargs.get(tool_name, {})
            instance_id, _ = await tool.create(create_kwargs=kwargs.get("create_kwargs", {}))
            tool_execution_response, tool_reward, res = await tool.execute(
                instance_id, tool_args, agent_data=agent_data
            )
        except Exception as e:
            logger.warning(f"Error when executing tool: {e}")
            # TODO: Hacky change just for my code exe tool...
            raw_current_code = process_generation_to_code(tool_args.get("code", ""))
            
            formatted_error = (f"{tool.code_result_start_tag}Error when executing tool: {e}{tool.code_result_end_tag}"
                if hasattr(tool, "code_result_start_tag") and hasattr(tool, "code_result_end_tag") else
                f"Error when executing tool: {e}"
            )

            return (
                ToolResponse(
                    text=formatted_error.strip(),
                ),
                0.0,
                { 
                    "code": raw_current_code,
                    "code_block_success": False, 
                    "code_block_exe_time": -1.0
                },
            )
            # return (
            #     ToolResponse(
            #         text=f"Error when executing tool: {e}",
            #     ),
            #     0.0,
            #     {},
            # )
        finally:
            if tool and instance_id:
                await tool.release(instance_id)

        tool_response_text = tool_execution_response.text
        if tool_response_text and len(tool_response_text) > self.max_tool_response_length:
            if self.tool_response_truncate_side == "left":
                tool_response_text = tool_response_text[: self.max_tool_response_length] + "...(truncated)"
            elif self.tool_response_truncate_side == "right":
                tool_response_text = "(truncated)..." + tool_response_text[-self.max_tool_response_length :]
            else:
                length = self.max_tool_response_length // 2
                tool_response_text = tool_response_text[:length] + "...(truncated)..." + tool_response_text[-length:]

        # Create ToolResponse from tool execution result
        tool_response_kwargs = {"text": tool_response_text}

        # Add multimedia data if present
        for attr_name in ["image", "video"]:
            if hasattr(tool_execution_response, attr_name):
                attr_value = getattr(tool_execution_response, attr_name)
                if attr_value is not None:
                    tool_response_kwargs[attr_name] = attr_value

        return ToolResponse(**tool_response_kwargs), tool_reward, res

    def _initialize_interactions(self, interaction_config_file):
        """Initialize interactions from configuration.
        Returns:
            dict[str, BaseInteraction]: A dictionary mapping interaction names to interaction instances.
        """
        if interaction_config_file is None:
            return {}

        interaction_map = initialize_interactions_from_config(interaction_config_file)
        return interaction_map
